version: '0.2'
sources:
- alias: sandbox
  target: sandbox
  type: local
  writeable: true
  filters: null
- alias: fup
  target: https://github.com/qxcodefup/arcade.git
  type: git
  writeable: false
  cache_timestamp: '2026-03-03 14:38:09'
  filters: null
expanded:
- fup@repositorio-de-problemas
- fup@campanha-principal
- fup@missão-operações
tasks: {}
flags:
  painel: 1
  quests: 1
  tracks: 0
  tasks: 0
  task_graph_mode: 0
  show_time: 0
lang: go
selected: sandbox@sandbox
